name: Release via Git Tags
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "some-prefix/*"
jobs:
  release-carbonmark-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/some-prefix/}" >> $GITHUB_ENV

      - name: Debug RELEASE_VERSION
        run: echo $RELEASE_VERSION

      - name: Get previous tag
        id: prev_tag
        run: |
          echo "::set-output name=tag::$(git tag --sort=-creatordate | grep '^some-prefix/' | head -n 2 | tail -n 1)"

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: some-prefix-${{ env.RELEASE_VERSION }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false
