name: Check version update

on:
  pull_request:
    paths:
      - "packageB/**"
      - "packageB/package.json"

jobs:
  check-version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version update
        run: |
          VERSION_CHANGED=$(git diff origin/${{ github.base_ref }}..${{ github.head_ref }} -- 'package.json' | grep '"version":')
          if [ -z "$VERSION_CHANGED" ]; then
            echo "You must update the version line in package.json when changing files in your-directory"
            exit 1
          fi
