name: Release via Git Tags
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "some-prefix/*"
jobs:
  release-carbonmark-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/some-prefix/}" >> $GITHUB_ENV

      - name: Debug RELEASE_VERSION
        run: echo $RELEASE_VERSION

      - name: Get previous tag
        id: prev_tag
        run: |
          echo "::set-output name=tag::$(git tag --sort=-creatordate | grep '^some-prefix/' | head -n 2 | tail -n 1)"

      - name: Generate release notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(git log ${{ steps.prev_tag.outputs.tag }}..${{ env.RELEASE_VERSION }} --pretty=format:"- %s (%an, %cd)" -- ./packageB)
          echo "::set-output name=body::$RELEASE_NOTES"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: some-prefix-${{ env.RELEASE_VERSION }}
          body: ${{ steps.release_notes.outputs.body }}
          draft: false
          prerelease: false
